import { Server } from "./types";
import hypixelBanner from "@/public/assets/images/hypixel/hypixelBanner.png";
import hypixeIcon from "@/public/assets/images/hypixel/hypixelIcon.png";

import cubeBanner from "@/public/assets/images/cubecraft/cubeBanner.png";
import cubeIcon from "@/public/assets/images/cubecraft/cubeIcon.png";

import PVPLBanner from "@/public/assets/images/pvplegacy/banner.png";
import PVPLIcon from "@/public/assets/images/pvplegacy/logo.png";

export const Servers: Server[] = [
  // DEMO data
  {
    id: "0",
    name: "Hypixel",
    description:
      "Hypixel is one of the world's largest Minecraft: Java Edition server networks, famous for its custom minigames like Bedwars, Skywars, and SkyBlock.",
    ip: "mc.hypixel.net",
    port: 25565,
    tags: ["minigames", "skyblock", "pvp", "adventure"],
    iconUrl: hypixeIcon.src,
    bannerUrl: hypixelBanner.src,
    supportedVersions: ["1.8.9", "1.21.10"],
    platforms: ["Java Edition"],
  },
  {
    id: "1",
    name: "CubeCraft",
    description:
      "CubeCraft is a popular Minecraft server network that offers a variety of multiplayer minigames and game modes. It's one of the largest Minecraft server communities, featuring games like SkyWars, EggWars, BlockWars, and various PvP (player versus player) modes.",
    ip: "play.cubecraft.net",
    port: 25565,
    tags: ["minigames", "pvp"],
    iconUrl: cubeIcon.src,
    bannerUrl: cubeBanner.src,
    supportedVersions: ["1.16.5", "1.21.10"],
    platforms: ["Java Edition", "Bedrock Edition"],
  },
  {
    id: "2",
    name: "PVP Legacy",
    description:
      "PVP Legacy is a competitive Minecraft server focused on pure PvP gameplay, featuring practice arenas, duels, and ranked matchmaking. Known for its high-quality combat experience and active community.",
    ip: "play.pvplegacy.net",
    port: 25565,
    tags: ["pvp", "kitpvp", "minigames", "community"],
    iconUrl: PVPLIcon.src,
    bannerUrl: PVPLBanner.src,
    supportedVersions: ["1.21.8"],
    platforms: ["Java Edition"],
  },
  {
    id: "3",
    name: "Localhost",
    description: "A local Minecraft server for testing and development.",
    ip: "localhost",
    port: 25565,
    tags: ["testing", "development"],
    supportedVersions: ["1.21.10"],
    platforms: ["Java Edition"],
  },
];

export const Tags: string[] = [
  // DEMO data
  "pvp",
  "skyblock",
  "minigames",
  "survival",
  "creative",
  "factions",
  "roleplay",
  "economy",
  "parkour",
  "adventure",
  "vanilla",
  "hardcore",
  "modded",
  "events",
  "building",
  "quests",
  "community",
  "redstone",
  "prison",
  "kitpvp",
  "towny",
];

export const platforms: string[] = ["Java Edition", "Bedrock Edition"];

export const versions: string[] = [
  // Release versions
  "1.21.10",
  "1.21.9",
  "1.21.8",
  "1.21.7",
  "1.21.6",
  "1.21.5",
  "1.21.4",
  "1.21.3",
  "1.21.2",
  "1.21.1",
  "1.21",
  "1.20.6",
  "1.20.5",
  "1.20.4",
  "1.20.3",
  "1.20.2",
  "1.20.1",
  "1.20",
  "1.19.4",
  "1.19.3",
  "1.19.2",
  "1.19.1",
  "1.19",
  "1.18.2",
  "1.18.1",
  "1.18",
  "1.17.1",
  "1.17",
  "1.16.5",
  "1.16.4",
  "1.16.3",
  "1.16.2",
  "1.16.1",
  "1.16",
  "1.15.2",
  "1.15.1",
  "1.15",
  "1.14.4",
  "1.14.3",
  "1.14.2",
  "1.14.1",
  "1.14",
  "1.13.2",
  "1.13.1",
  "1.13",
  "1.12.2",
  "1.12.1",
  "1.12",
  "1.11.2",
  "1.11.1",
  "1.11",
  "1.10.2",
  "1.10.1",
  "1.10",
  "1.9.4",
  "1.9.3",
  "1.9.2",
  "1.9.1",
  "1.9",
  "1.8.9",
  "1.8.8",
  "1.8.7",
  "1.8.6",
  "1.8.5",
  "1.8.4",
  "1.8.3",
  "1.8.2",
  "1.8.1",
  "1.8",
  "1.7.10",
  "1.7.9",
  "1.7.8",
  "1.7.7",
  "1.7.6",
  "1.7.5",
  "1.7.4",
  "1.7.2",
  "1.6.4",
  "1.6.2",
  "1.6.1",
  "1.5.2",
  "1.5.1",
  "1.5",
  "1.4.7",
  "1.4.6",
  "1.4.5",
  "1.4.4",
  "1.4.2",
  "1.3.2",
  "1.3.1",
  "1.2.5",
  "1.2.4",
  "1.2.3",
  "1.2.2",
  "1.2.1",
  "1.1",
  "1.0",
];
